### ISSUE TITLE
Add parameter to disable 'enable button'

### ISSUE THREAD

**Issue by ghost** [ros2/teleop_twist_joy#20]
As a user of this package I would like the ability to use this node without holding an enable button (deadman switch).

In my project I would like to make use of this node to convert an existing Joy topic in the system to a Twist message. However, the existing topic does not make use of an enable button and I cannot really change it. 

I can volunteer to make this change.

**Comment by clalancette** [comment]
Sure, I think it makes sense to add a new parameter which is something like "require_enable_button".  I would default it to true (maintaining the current behavior), but allow the user to override it.

Patches to implement it are welcome!

**Comment by kgibsonjca** [comment]
> 
> 
> Sure, I think it makes sense to add a new parameter which is something like "require_enable_button". I would default it to true (maintaining the current behavior), but allow the user to override it.
> 
> Patches to implement it are welcome!

How about accepting -1 for the enable_button parameter as is done with the enable_turbo_button?

**Comment by ghost** [comment]
@clalancette I've created a PR for this feature
