### ISSUE TITLE
Parameters are incorrectly documented

### ISSUE THREAD

**Issue by joshnewans** [ros2/teleop_twist_joy#23]
This package is great, but many of the parameters are incorrectly documented (or implemented, but I assume it's just the documentation).

For example, according to the README:

- `axis_angular (int, default: 0)`
  - Joystick axis to use for angular movement control.
  
- `axis_linear (int, default: 1)`
  - Joystick axis to use for linear movement control.

It seems that #3 changed the default joystick mapping to axes 2 and 5 which is fine (on my Xbox controller that now maps to left and right trigger instead which is annoying, but I guess that's the point of being able to remap them), however the documentation should be updated to reflect the new defaults.

What I found more confusing is that the parameters `axis_angular` and `axis_linear` (as well as a bunch of the others) don't seem to work anymore. I had to use `axis_angular.yaw` and `axis_linear.x`. I think this is a sensible move since it allows mapping to the other axes of `/cmd_vel`, but again the documentation is lacking (or I have gotten myself confused, in which case my apologies).

Also, is it reasonable (or even possible) for `axis_angular` and co. to be aliases for their `yaw` and `x` counterparts?

I can have a go at reading through the main cpp file and updating the README accordingly, but it would probably be better done by someone who actually knows what that code is doing.

P.S. I found it helpful when I started with ROS (1) that the `teleop_twist_joy` package worked out of the box with my Xbox controller. Although that hasn't been the case for this package, the provided launch files are a great way to make it easier for new users. Unfortunately in my situation it wasn't so smooth since they don't utilise the `joy_linux` package (which I use to avoid mapping individual events through Docker), and the Xbox button layout config seems to be incorrect, however these are separate issues. 
At some point I might confirm that the Xbox config is not just my problem and submit a PR for it.

Thanks!

**Comment by joshnewans** [comment]
I just noticed that PR #18 was a fairly thorough rewrite of the README only a few months ago so I'm wondering if I missed something?

If not let me know and I'll have a go at clearing things up.

**Comment by clalancette** [comment]
> I just noticed that PR #18 was a fairly thorough rewrite of the README only a few months ago so I'm wondering if I missed something?
> 
> If not let me know and I'll have a go at clearing things up.

No, you are totally correct.  When we did #18, I just totally forgot that each of the axes has an x, y, and z component.  A PR to add that would be welcome!
