### ISSUE TITLE
teleop-launch.py not found

### ISSUE THREAD

**Issue by RealBadDad** [ros2/teleop_twist_joy#25]
installed as the instructions and ran as followed but the teleop-launch.py file seems to be missing

sudo apt-get install ros-dashing-teleop-twist-joy 

ros2 launch teleop_twist_joy teleop-launch.py joy_config:='xbox'

**Comment by clalancette** [comment]
So at the time we released Dashing, we had not yet ported the `teleop-launch.py` to ROS 2.  We have now done this in the "Foxy" branch (likely where you were reading the instructions), but we haven't backported to Dashing.  Given that Dashing is End-of-Life in a couple of months, I'm inclined to just leave this as-is and say that you'll need to use newer ROS 2 to get the `teleop-launch.py` functionality.

Thanks anyway for the bug report, I'm going to close this.
