### ISSUE TITLE
Launch file setting a deprecated param?

### ISSUE THREAD

**Issue by artivis** [ros2/teleop_twist_joy#38]
Hello,

Looking at the launch file it seems to be setting a [`dev` parameter for the `joy_node`](https://github.com/ros2/teleop_twist_joy/blob/1a43f435401b7c40e7dc0d5954e6ce57f961d382/launch/teleop-launch.py#L26) that doesn't exists. Instead, the `joy_node` uses [`device_id`](https://github.com/ros-drivers/joystick_drivers/blob/09082e3567f147b9721c401fba74d42eb9847636/joy/src/joy.cpp#L54), since, afaict, [its port to ROS 2](https://github.com/clalancette/joystick_drivers/blob/f32bd582066a82d19a0a572fa0c3939354970345/joy/src/joy.cpp#L54).  
Am I missing something or has this been broken forever in ROS 2?

**Comment by clalancette** [comment]
> Am I missing something or has this been broken forever in ROS 2?

It hasn't been broken forever, but it has been broken quite a while.  The history of the node to control joysticks in ROS 2 is a little twisted.  The story below probably isn't all that relevant, but it is fun to walk down memory lane a little.

The original code of any kind of joystick control to ROS 2 was in 2016 as part of the [turtlebot2_demo](https://github.com/ros2/turtlebot2_demo) repository.  That code was written from scratch to look at the `/dev/input/js0` input device from Linux.  This is equivalent in spirit to how the joystick driver in ROS 1 works, but is a very different and simplified implementation.  It doesn't have *any* parameters at all; everything is hard-coded.

That code eventually got split out into its own repository in [joystick_drivers_from_scratch](https://github.com/ros2/joystick_drivers_from_scratch).  This also didn't have any parameters at all, everything is hard-coded.

Somewhat in parallel with `joystick_drivers_from_scratch`, [joystick_drivers](https://github.com/ros2/joystick_drivers) was forked off of the original https://github.com/ros/joystick_drivers, and a full port to ROS 2 was done.  That version did have parameters, and the parameter in question was indeed called `dev`.  It was around this time that the launch file here in `teleop_twist_joy` was created.  At that time, the parameter was correct.

In 2020, I decided that we needed a cross-platform joystick driver, particularly one that would work in Windows.  So I wrote an entirely new version based on SDL, which is the node we call "joy" today.  That one was contributed to the upstream https://github.com/ros/joystick_drivers, and the old https://github.com/ros2/joystick_drivers and https://github.com/ros2/joystick_drivers_from_scratch were both deprecated.  One other thing to note here is that I wasn't entirely confident that my SDL port would be sufficient, so retained the old, Linux-only joystick driver as "joy_linux".  The new "joy" node uses the `device_id` parameter, while the old "joy_linux" node uses the `dev` parameter.

All of that said, you are correct that nowadays that parameter should indeed be changed to `device_id`.  If you'd like to submit a pull request, I'd be happy to review it.

**Comment by clalancette** [comment]
This was fixed by #52 , so closing.
